services:
  db:
    image: mysql:9.6.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: blog-admin
      MYSQL_PASSWORD: blog-admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
